"""Convert a Packmol PDB to a LAMMPS `atom_style full` data file.

Groups atoms into water molecules and writes O,H,H atom ordering with MB-pol
charges and masses.

Usage: python pdb_to_lammps.py --pdb INPUT.pdb --nwaters N --lx LX --out OUTPUT.data
"""

import argparse
import sys

CHARGE_O = -1.1128
CHARGE_H =  0.5564
MASS_O   = 15.9994
MASS_H   =  1.00794


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pdb",     required=True)
    p.add_argument("--nwaters", type=int,   required=True)
    p.add_argument("--lx",      type=float, required=True)
    p.add_argument("--out",     required=True)
    args = p.parse_args()

    # read all ATOM / HETATM records
    raw = []
    with open(args.pdb) as f:
        for line in f:
            if line.startswith(("ATOM", "HETATM")):
                name = line[12:16].strip()
                x    = float(line[30:38])
                y    = float(line[38:46])
                z    = float(line[46:54])
                raw.append((name, x, y, z))

    expected = args.nwaters * 3
    if len(raw) != expected:
        sys.exit(f"ERROR: Expected {expected} atoms in PDB, got {len(raw)}.")

    # group into per-molecule triplets; identify O and H by atom name
    atoms  = []   # (mol_id, type, charge, x, y, z)
    bonds  = []   # (bond_id, btype, a1, a2)
    angles = []   # (ang_id, atype, a1_H, a2_O, a3_H)

    for i in range(0, len(raw), 3):
        mol_id    = i // 3 + 1
        group     = raw[i : i + 3]
        oxygens   = [(n, x, y, z) for n, x, y, z in group if n.upper().startswith("O")]
        hydrogens = [(n, x, y, z) for n, x, y, z in group if n.upper().startswith("H")]

        if len(oxygens) != 1 or len(hydrogens) != 2:
            sys.exit(
                f"ERROR: Molecule {mol_id} (PDB lines {i+1}–{i+3}) has "
                f"{len(oxygens)} oxygen(s) and {len(hydrogens)} hydrogen(s). "
                f"Each water molecule must contain exactly 1 O and 2 H atoms."
            )

        base = len(atoms) + 1          # 1-based atom ID of this molecule's O
        _, ox, oy, oz = oxygens[0]

        # O first, then H1, H2  (order required by MBX)
        atoms.append((mol_id, 1, CHARGE_O, ox, oy, oz))
        atoms.append((mol_id, 2, CHARGE_H, hydrogens[0][1], hydrogens[0][2], hydrogens[0][3]))
        atoms.append((mol_id, 2, CHARGE_H, hydrogens[1][1], hydrogens[1][2], hydrogens[1][3]))

        o_id, h1_id, h2_id = base, base + 1, base + 2
        bonds.append((2 * (mol_id - 1) + 1, 1, o_id, h1_id))
        bonds.append((2 * (mol_id - 1) + 2, 1, o_id, h2_id))
        angles.append((mol_id, 1, h1_id, o_id, h2_id))

    lx = args.lx
    with open(args.out, "w") as f:
        f.write(
            f"LAMMPS data file — {args.nwaters} H2O cubic box  "
            f"{lx:.4f} × {lx:.4f} × {lx:.4f} Å  "
            f"(generated by pdb_to_lammps.py)\n\n"
        )
        f.write(f"{len(atoms)} atoms\n2 atom types\n")
        f.write(f"{len(bonds)} bonds\n1 bond types\n")
        f.write(f"{len(angles)} angles\n1 angle types\n\n")
        f.write(f"0 {lx:.6f} xlo xhi\n")
        f.write(f"0 {lx:.6f} ylo yhi\n")
        f.write(f"0 {lx:.6f} zlo zhi\n\n")

        f.write("Masses\n\n")
        f.write(f"1 {MASS_O}  # O (MB-pol)\n")
        f.write(f"2 {MASS_H}  # H (MB-pol)\n")

        f.write("\nAtoms # full\n\n")
        for aid, (mol, atype, q, x, y, z) in enumerate(atoms, 1):
            f.write(
                f"{aid:6d} {mol:6d} {atype} {q:8.4f} "
                f"{x:14.8f} {y:14.8f} {z:14.8f} 0 0 0\n"
            )

        f.write("\nBonds\n\n")
        for b in bonds:
            f.write(f"{b[0]} {b[1]} {b[2]} {b[3]}\n")

        f.write("\nAngles\n\n")
        for a in angles:
            f.write(f"{a[0]} {a[1]} {a[2]} {a[3]} {a[4]}\n")

    print(f"  {len(atoms)} atoms / {len(bonds)} bonds / {len(angles)} angles → {args.out}")


if __name__ == "__main__":
    main()
